# Generated by Django 5.1.3 on 2025-11-05 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('instructions', models.TextField(verbose_name='Instruções')),
                ('notebook_template', models.FileField(upload_to='challenges/templates/', verbose_name='Template do Notebook')),
                ('dataset_file', models.FileField(blank=True, null=True, upload_to='challenges/datasets/', verbose_name='Arquivo de Dataset')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', max_length=20, verbose_name='Status')),
                ('metric_type', models.CharField(default='accuracy', max_length=50, verbose_name='Tipo de Métrica')),
                ('coins_reward', models.IntegerField(default=10, verbose_name='Recompensa em Moedas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Publicação')),
                ('created_by', models.ForeignKey(limit_choices_to={'user_type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Desafio',
                'verbose_name_plural': 'Desafios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_number', models.IntegerField(verbose_name='Número da Cópia')),
                ('notebook_file', models.FileField(upload_to='challenges/copies/', verbose_name='Arquivo do Notebook')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='Submetido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='challenges.challenge')),
                ('participant', models.ForeignKey(limit_choices_to={'user_type': 'participant'}, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_copies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cópia de Desafio',
                'verbose_name_plural': 'Cópias de Desafios',
                'ordering': ['-created_at'],
                'unique_together': {('challenge', 'participant', 'copy_number')},
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(verbose_name='Acurácia')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='Tempo de Execução (s)')),
                ('code_snapshot', models.TextField(verbose_name='Snapshot do Código')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Submissão')),
                ('challenge_copy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='challenges.challengecopy')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.team')),
            ],
            options={
                'verbose_name': 'Submissão',
                'verbose_name_plural': 'Submissões',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
