# Generated by Django 5.1.3 on 2025-11-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='notebook_template',
            field=models.FileField(blank=True, null=True, upload_to='challenges/templates/', verbose_name='Template do Notebook'),
        ),
    ]
