# Generated by Django 5.1.3 on 2025-11-05 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_accuracy', models.FloatField(default=0.0, verbose_name='Melhor Acurácia')),
                ('total_submissions', models.IntegerField(default=0, verbose_name='Total de Submissões')),
                ('rank', models.IntegerField(default=0, verbose_name='Posição')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('best_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenges.submission')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entry', to='users.team')),
            ],
            options={
                'verbose_name': 'Entrada do Leaderboard',
                'verbose_name_plural': 'Entradas do Leaderboard',
                'ordering': ['-best_accuracy', 'updated_at'],
            },
        ),
    ]
